import { createHmac, timingSafeEqual, randomBytes } from "crypto";
import { NextRequest, NextResponse } from "next/server";

// ─── Constants ────────────────────────────────────────────────────────────────

export const CSRF_COOKIE = "csrf-token";
export const CSRF_HEADER = "x-csrf-token";
const TOKEN_TTL_MS = 24 * 60 * 60 * 1000; // 24 hours

// ─── Secret ───────────────────────────────────────────────────────────────────
//
// Lazy validation: we only throw when a CSRF operation is actually attempted,
// not at module load / build time.

function getSecret(): string {
  const secret = process.env.CSRF_SECRET;
  if (!secret) {
    throw new Error(
      "CSRF_SECRET is not set. " +
      "Generate one with: node -e \"console.log(require('crypto').randomBytes(32).toString('base64'))\" " +
      "and add it to .env as CSRF_SECRET=<value>"
    );
  }
  return secret;
}

// ─── Token format ─────────────────────────────────────────────────────────────
//
// Structure: {expiresAtMs}.{randomHex64}.{hmacHex64}
//
//   expiresAtMs  — Unix timestamp (ms) when the token expires
//   randomHex64  — 32 cryptographically random bytes as hex (128-bit uniqueness)
//   hmacHex64    — HMAC-SHA256(CSRF_SECRET, "{expiresAtMs}.{randomHex64}")
//
// The HMAC signature means:
//   • The token can only be generated by a server that knows CSRF_SECRET
//   • A subdomain attacker can SET a cookie but cannot generate a valid signature
//   • The expiry is integrity-protected — tampering with it invalidates the HMAC

// ─── Token generation ─────────────────────────────────────────────────────────

export function generateCsrfToken(): string {
  const expiresAt = String(Date.now() + TOKEN_TTL_MS);
  const random = randomBytes(32).toString("hex"); // 64 hex chars
  const payload = `${expiresAt}.${random}`;
  const hmac = createHmac("sha256", getSecret()).update(payload).digest("hex");
  return `${payload}.${hmac}`;
}

// ─── Token validation ─────────────────────────────────────────────────────────

export function validateCsrfTokenSignature(token: string): boolean {
  // Token has exactly two dots: {expiresAt}.{random}.{hmac}
  // We find the first and last dots to split it robustly.
  const firstDot = token.indexOf(".");
  const lastDot = token.lastIndexOf(".");

  if (firstDot === -1 || firstDot === lastDot) return false; // wrong structure

  const payload = token.slice(0, lastDot);       // "{expiresAt}.{random}"
  const expiresAt = token.slice(0, firstDot);    // "{expiresAt}"
  const signature = token.slice(lastDot + 1);   // "{hmac}"

  // Reject expired tokens before doing crypto — avoids wasting CPU on stale tokens.
  const expiresAtMs = Number(expiresAt);
  if (!Number.isFinite(expiresAtMs) || expiresAtMs < Date.now()) return false;

  // Recompute the expected HMAC
  const expectedHmac = createHmac("sha256", getSecret()).update(payload).digest("hex");

  // Parse signature and expected into byte buffers for constant-time comparison.
  // Buffer.from(hexStr, "hex") silently truncates on odd-length or invalid chars.
  // We check lengths first to ensure timingSafeEqual receives equal-length buffers.
  const sigBuf = Buffer.from(signature, "hex");
  const expBuf = Buffer.from(expectedHmac, "hex");

  if (sigBuf.length !== expBuf.length) return false; // wrong-length → definitely invalid

  // timingSafeEqual prevents timing side-channel attacks.
  // A naive `===` would leak the number of matching bytes through response time.
  return timingSafeEqual(sigBuf, expBuf);
}

// ─── Cookie helper ────────────────────────────────────────────────────────────
//
// MUST use httpOnly: false — JavaScript must be able to read this value and
// send it as a request header. If httpOnly were true, the JS-accessible half of
// the double-submit pattern would break entirely.
//
// sameSite: "strict" is used here (not "lax") because this cookie holds
// security-sensitive data, not a session. Strict means it is never sent by the
// browser on any cross-site request — but we don't rely on the browser sending
// it; we rely on our JS reading it and setting a header.

export function setCsrfCookie(response: NextResponse, token: string): void {
  response.cookies.set(CSRF_COOKIE, token, {
    httpOnly: false, // intentional — JS must read this
    secure: process.env.NODE_ENV === "production",
    sameSite: "strict",
    maxAge: TOKEN_TTL_MS / 1000, // seconds
    path: "/",
  });
}

// ─── Request validation ───────────────────────────────────────────────────────
//
// This is the function called at the top of every state-changing route handler,
// identical in usage to checkRateLimit:
//
//   const csrfError = checkCsrf(req);
//   if (csrfError) return csrfError;
//
// It performs three independent checks in order of cheapest to most expensive:
//   1. Method guard   — safe methods are skipped entirely
//   2. Origin check   — header-level, no crypto
//   3. Token check    — HMAC verify + double-submit match

export function checkCsrf(req: NextRequest): NextResponse | null {
  // ── Guard: skip safe methods ────────────────────────────────────────────────
  // GET / HEAD / OPTIONS do not change state. CSRF is only a risk for mutations.
  if (["GET", "HEAD", "OPTIONS"].includes(req.method)) return null;

  // ── Layer 1: Origin validation ──────────────────────────────────────────────
  //
  // Browsers set the Origin header on all cross-origin requests. If Origin is
  // present and doesn't match our host, the request is definitely cross-site.
  //
  // We don't reject requests with no Origin: same-origin requests from the
  // browser's navigation (e.g., a form POST) may omit it, and server-to-server
  // calls from our own backend won't have it either.
  const origin = req.headers.get("origin");
  if (origin) {
    const host = req.headers.get("host") ?? "";
    const proto = req.headers.get("x-forwarded-proto") ?? "https";
    const expectedOrigin = `${proto}://${host}`;
    try {
      if (new URL(origin).origin !== expectedOrigin) {
        return NextResponse.json(
          { error: "Forbidden: request origin is not allowed." },
          { status: 403 }
        );
      }
    } catch {
      // Unparseable origin — treat as hostile
      return NextResponse.json(
        { error: "Forbidden: malformed origin." },
        { status: 403 }
      );
    }
  }

  // ── Layer 2: CSRF token double-submit check ─────────────────────────────────
  //
  // The frontend must read the csrf-token cookie (non-httpOnly) and send its
  // value in the X-CSRF-Token header. The server checks:
  //   a) Both are present
  //   b) They are identical (double-submit: attacker can't read the cookie from
  //      a different origin, so they can't construct a matching header)
  //   c) The value carries a valid HMAC signature (subdomain-attack resistance)

  const headerToken = req.headers.get(CSRF_HEADER);
  const cookieToken = req.cookies.get(CSRF_COOKIE)?.value;

  if (!headerToken || !cookieToken) {
    return NextResponse.json(
      { error: "Forbidden: CSRF token missing." },
      { status: 403 }
    );
  }

  // Double-submit: constant-time comparison to prevent timing leaks
  const headerBuf = Buffer.from(headerToken);
  const cookieBuf = Buffer.from(cookieToken);
  const tokensMatch =
    headerBuf.length === cookieBuf.length &&
    timingSafeEqual(headerBuf, cookieBuf);

  if (!tokensMatch) {
    return NextResponse.json(
      { error: "Forbidden: CSRF token mismatch." },
      { status: 403 }
    );
  }

  // HMAC signature + expiry check
  if (!validateCsrfTokenSignature(headerToken)) {
    return NextResponse.json(
      { error: "Forbidden: CSRF token invalid or expired." },
      { status: 403 }
    );
  }

  return null; // all checks passed — allow the request
}
