// AUTO-GENERATED by scripts/import-curriculum.ts — do not edit by hand.
//
// What the public subject pages show for each subject that comes from the
// curriculum sheets, summarised from prisma/curriculum.data.ts. Regenerate
// with `npx tsx scripts/import-curriculum.ts --landing`.

import type { LandingCategory } from "./subjects";

export const GENERATED_CURRICULUM: Record<string, LandingCategory[]> = {
  "MATH": [
    {
      "name": "Quantitative Problem Solving",
      "weight": 45,
      "topics": [
        {
          "name": "Number Sense",
          "subtopics": [
            {
              "name": "Fractions",
              "description": "Read, compare, and compute with fractions and mixed numbers, including unlike denominators.",
              "minutes": 430,
              "level": 1,
              "videos": 88,
              "articles": 0
            },
            {
              "name": "Decimals",
              "description": "Read place value and add, subtract, multiply, and divide decimals.",
              "minutes": 208,
              "level": 1,
              "videos": 36,
              "articles": 0
            },
            {
              "name": "Positive & negative numbers",
              "description": "Add, subtract, multiply, and divide signed numbers, and interpret absolute value.",
              "minutes": 150,
              "level": 1,
              "videos": 26,
              "articles": 0
            },
            {
              "name": "Factors & Multiples",
              "description": "Find factors, multiples, GCF, LCM, and prime factorisations.",
              "minutes": 68,
              "level": 1,
              "videos": 10,
              "articles": 0
            },
            {
              "name": "Exponents & roots",
              "description": "Apply exponent rules and evaluate square and cube roots.",
              "minutes": 202,
              "level": 2,
              "videos": 30,
              "articles": 0
            },
            {
              "name": "Scientific notation",
              "description": "Convert between standard and scientific notation and compute with it.",
              "minutes": 76,
              "level": 2,
              "videos": 11,
              "articles": 0
            }
          ]
        },
        {
          "name": "Ratios, Rates and Proportion",
          "subtopics": [
            {
              "name": "Ratios",
              "description": "Write and compare ratios and unit rates, and solve rate problems.",
              "minutes": 80,
              "level": 1,
              "videos": 13,
              "articles": 0
            },
            {
              "name": "Percentages",
              "description": "Calculate percent of a number, percent change, discount, markup, tax, and tip.",
              "minutes": 40,
              "level": 2,
              "videos": 11,
              "articles": 0
            },
            {
              "name": "Proportions",
              "description": "Set up and solve proportions, including scale and constant-of-proportionality problems.",
              "minutes": 140,
              "level": 2,
              "videos": 28,
              "articles": 0
            }
          ]
        },
        {
          "name": "Data and Statistics",
          "subtopics": [
            {
              "name": "Mean, median, mode, range",
              "description": "Calculate mean, median, mode, range, and weighted average, and judge the effect of outliers.",
              "minutes": 217,
              "level": 2,
              "videos": 23,
              "articles": 0
            },
            {
              "name": "Bar & circle graphs",
              "description": "Read and interpret bar graphs, circle graphs, and pictographs.",
              "minutes": 56,
              "level": 1,
              "videos": 12,
              "articles": 0
            },
            {
              "name": "Dot plots, histograms & box plots",
              "description": "Build and interpret dot plots, histograms, and box plots, including shape and spread.",
              "minutes": 147,
              "level": 2,
              "videos": 20,
              "articles": 0
            },
            {
              "name": "Scatter plots",
              "description": "Describe association in a scatter plot and use a line of best fit to make predictions.",
              "minutes": 266,
              "level": 2,
              "videos": 30,
              "articles": 0
            },
            {
              "name": "Probability",
              "description": "Find probabilities of simple and compound events, including independent and dependent events.",
              "minutes": 330,
              "level": 2,
              "videos": 38,
              "articles": 0
            }
          ]
        },
        {
          "name": "Geometric Measurement",
          "subtopics": [
            {
              "name": "Area & perimeter",
              "description": "Calculate area and perimeter of rectangles, triangles, and composite figures.",
              "minutes": 98,
              "level": 2,
              "videos": 21,
              "articles": 0
            },
            {
              "name": "Surface area & volume",
              "description": "Calculate surface area and volume of prisms, cylinders, cones, spheres, and pyramids.",
              "minutes": 82,
              "level": 3,
              "videos": 13,
              "articles": 0
            },
            {
              "name": "Circles",
              "description": "Calculate circumference, area, radius, and diameter of circles.",
              "minutes": 37,
              "level": 2,
              "videos": 6,
              "articles": 0
            },
            {
              "name": "Pythagorean theorem",
              "description": "Apply the Pythagorean theorem to find missing side lengths in right triangles.",
              "minutes": 74,
              "level": 3,
              "videos": 11,
              "articles": 0
            }
          ]
        }
      ]
    },
    {
      "name": "Algebraic Reasoning",
      "weight": 55,
      "topics": [
        {
          "name": "Expressions and Polynomials",
          "subtopics": [
            {
              "name": "Variables & expressions",
              "description": "Write, evaluate, and simplify algebraic expressions using the properties of operations.",
              "minutes": 64,
              "level": 2,
              "videos": 14,
              "articles": 0
            }
          ]
        },
        {
          "name": "Equations and Inequalities",
          "subtopics": [
            {
              "name": "Solving equations & inequalities",
              "description": "Solve one- and two-step linear equations and inequalities, including word problems.",
              "minutes": 193,
              "level": 2,
              "videos": 28,
              "articles": 0
            },
            {
              "name": "Systems of equations",
              "description": "Solve systems of two linear equations by graphing, substitution, and elimination.",
              "minutes": 160,
              "level": 3,
              "videos": 20,
              "articles": 0
            }
          ]
        },
        {
          "name": "Graphs and Functions",
          "subtopics": [
            {
              "name": "Slope & linear functions",
              "description": "Find slope and intercepts, and graph and interpret linear functions.",
              "minutes": 171,
              "level": 3,
              "videos": 21,
              "articles": 0
            },
            {
              "name": "Quadratic functions",
              "description": "Factor, solve, and graph quadratic expressions and functions.",
              "minutes": 196,
              "level": 4,
              "videos": 28,
              "articles": 0
            }
          ]
        }
      ]
    }
  ],
  "SS": [
    {
      "name": "Civics & Government",
      "weight": 50,
      "topics": [
        {
          "name": "Foundations of Government",
          "subtopics": [
            {
              "name": "Types of Government & Constitutional Principles",
              "description": "Compare forms of government and explain the principles behind the US Constitution: popular sovereignty, separation of powers, checks and balances, and federalism.",
              "minutes": 600,
              "level": 2,
              "videos": 33,
              "articles": 32
            },
            {
              "name": "Founding Documents",
              "description": "Read and interpret the Declaration of Independence, the Articles of Confederation and the Constitution as primary sources.",
              "minutes": 166,
              "level": 3,
              "videos": 3,
              "articles": 5
            },
            {
              "name": "Branches of government",
              "description": "Describe the powers of Congress, the presidency and the courts, and how each branch checks the others.",
              "minutes": 436,
              "level": 2,
              "videos": 32,
              "articles": 23
            }
          ]
        },
        {
          "name": "Rights & Civic Participation",
          "subtopics": [
            {
              "name": "Bill of Rights & amendments",
              "description": "Explain the rights protected by the Bill of Rights and later amendments, and how courts have applied them.",
              "minutes": 295,
              "level": 2,
              "videos": 13,
              "articles": 19
            },
            {
              "name": "Elections & political parties",
              "description": "Explain how elections, campaigns and political parties work in the United States.",
              "minutes": 227,
              "level": 2,
              "videos": 19,
              "articles": 13
            },
            {
              "name": "Citizenship & civic responsibilities",
              "description": "Describe the rights and responsibilities of citizens and how citizenship is gained.",
              "minutes": 169,
              "level": 1,
              "videos": 20,
              "articles": 6
            },
            {
              "name": "Contemporary public policy",
              "description": "Analyze how political ideology, public opinion and government institutions shape current policy debates.",
              "minutes": 143,
              "level": 3,
              "videos": 14,
              "articles": 5
            }
          ]
        }
      ]
    },
    {
      "name": "U.S. History",
      "weight": 20,
      "topics": [
        {
          "name": "Founding to Reconstruction",
          "subtopics": [
            {
              "name": "Colonial America + Revolutionary Era",
              "description": "Trace colonial settlement, the causes of the American Revolution and the founding of the new nation.",
              "minutes": 547,
              "level": 2,
              "videos": 33,
              "articles": 33
            },
            {
              "name": "Civil War & Reconstruction",
              "description": "Explain the causes, major events and outcomes of the Civil War and Reconstruction.",
              "minutes": 329,
              "level": 2,
              "videos": 25,
              "articles": 5
            }
          ]
        },
        {
          "name": "Modern America",
          "subtopics": [
            {
              "name": "World Wars I & II",
              "description": "Explain US involvement in World War I and World War II and their effects at home and abroad.",
              "minutes": 334,
              "level": 2,
              "videos": 19,
              "articles": 25
            },
            {
              "name": "Cold War",
              "description": "Describe the rivalry between the US and the Soviet Union and its major conflicts and policies.",
              "minutes": 248,
              "level": 3,
              "videos": 6,
              "articles": 23
            },
            {
              "name": "Civil Rights Movement",
              "description": "Explain the goals, strategies and key events of the civil rights movement.",
              "minutes": 108,
              "level": 2,
              "videos": 0,
              "articles": 17
            },
            {
              "name": "Foreign Policy after 9/11",
              "description": "Analyze US foreign policy from the late Cold War through the September 11 attacks and the war on terror.",
              "minutes": 102,
              "level": 3,
              "videos": 3,
              "articles": 13
            }
          ]
        }
      ]
    },
    {
      "name": "Economics",
      "weight": 15,
      "topics": [
        {
          "name": "Microeconomics",
          "subtopics": [
            {
              "name": "Supply, demand, market equilibrium",
              "description": "Use supply and demand to explain prices, shortages, surpluses and market equilibrium.",
              "minutes": 133,
              "level": 2,
              "videos": 15,
              "articles": 2
            },
            {
              "name": "Basic Economic Concepts",
              "description": "Apply scarcity, opportunity cost and market structures such as monopoly to economic decisions.",
              "minutes": 460,
              "level": 3,
              "videos": 45,
              "articles": 2
            }
          ]
        },
        {
          "name": "Macroeconomics",
          "subtopics": [
            {
              "name": "Banking & financial sector",
              "description": "Explain how banks, money, interest and financial markets work.",
              "minutes": 277,
              "level": 3,
              "videos": 28,
              "articles": 0
            },
            {
              "name": "Fiscal policy & government spending",
              "description": "Explain how taxes and government spending affect aggregate demand and the economy.",
              "minutes": 249,
              "level": 4,
              "videos": 17,
              "articles": 8
            },
            {
              "name": "GDP/inflation/unemployment",
              "description": "Measure economic performance with GDP, inflation and unemployment, and describe the business cycle.",
              "minutes": 261,
              "level": 3,
              "videos": 24,
              "articles": 9
            }
          ]
        }
      ]
    },
    {
      "name": "Geography & the World",
      "weight": 15,
      "topics": [
        {
          "name": "World History",
          "subtopics": [
            {
              "name": "World history beginnings",
              "description": "Trace early humans, the rise of agrarian societies and the first empires and belief systems.",
              "minutes": 1365,
              "level": 2,
              "videos": 63,
              "articles": 99
            }
          ]
        },
        {
          "name": "Geography",
          "subtopics": [
            {
              "name": "Resources and society",
              "description": "Explain how natural resources and the environment shaped early agrarian societies.",
              "minutes": 346,
              "level": 2,
              "videos": 12,
              "articles": 31
            },
            {
              "name": "Migration",
              "description": "Explain why people migrate and how population growth and urbanization change places.",
              "minutes": 56,
              "level": 2,
              "videos": 4,
              "articles": 0
            },
            {
              "name": "Borders, Regions & Geographic Tools",
              "description": "Use maps and geographic tools, and explain how regions and borders are defined and contested.",
              "minutes": 103,
              "level": 2,
              "videos": 7,
              "articles": 0
            }
          ]
        }
      ]
    }
  ],
  "SCI": [
    {
      "name": "Life Science",
      "weight": 40,
      "topics": [
        {
          "name": "Cells & Energy",
          "subtopics": [
            {
              "name": "Cell Parts and Their Functions",
              "description": "Identify the organelles of plant and animal cells and describe what each does.",
              "minutes": 32,
              "level": 1,
              "videos": 2,
              "articles": 5
            },
            {
              "name": "Photosynthesis",
              "description": "Explain how plants turn light, water and carbon dioxide into glucose and oxygen.",
              "minutes": 29,
              "level": 2,
              "videos": 2,
              "articles": 2
            },
            {
              "name": "Cellular Respiration",
              "description": "Explain how cells release energy from glucose, with and without oxygen.",
              "minutes": 18,
              "level": 2,
              "videos": 1,
              "articles": 2
            },
            {
              "name": "Cell Theory",
              "description": "State the principles of cell theory and compare prokaryotic and eukaryotic cells.",
              "minutes": 16,
              "level": 1,
              "videos": 1,
              "articles": 2
            },
            {
              "name": "Mitosis & Meiosis",
              "description": "Compare how cells divide by mitosis and meiosis and why each matters.",
              "minutes": 150,
              "level": 3,
              "videos": 9,
              "articles": 6
            }
          ]
        },
        {
          "name": "Human Body & Health",
          "subtopics": [
            {
              "name": "Human Body Systems",
              "description": "Describe how the digestive, respiratory, nervous and immune systems work and interact.",
              "minutes": 90,
              "level": 2,
              "videos": 6,
              "articles": 9
            },
            {
              "name": "Homeostasis",
              "description": "Explain how the body keeps conditions such as temperature and blood sugar stable.",
              "minutes": 25,
              "level": 2,
              "videos": 1,
              "articles": 3
            },
            {
              "name": "Nutrition",
              "description": "Describe the nutrients the body needs and how diet affects health.",
              "minutes": 58,
              "level": 1,
              "videos": 6,
              "articles": 4
            },
            {
              "name": "Disease & Pathogens",
              "description": "Explain how bacteria, viruses and other pathogens cause disease and how the body and medicine fight them.",
              "minutes": 190,
              "level": 2,
              "videos": 14,
              "articles": 2
            }
          ]
        },
        {
          "name": "Heredity & Evolution",
          "subtopics": [
            {
              "name": "DNA & Heredity",
              "description": "Describe DNA's structure and predict inheritance with Punnett squares.",
              "minutes": 350,
              "level": 3,
              "videos": 22,
              "articles": 16
            },
            {
              "name": "Evolution & Natural Selection",
              "description": "Explain how natural selection drives evolution and the evidence for it.",
              "minutes": 107,
              "level": 3,
              "videos": 5,
              "articles": 5
            }
          ]
        },
        {
          "name": "Ecosystems",
          "subtopics": [
            {
              "name": "Food Webs & Energy Flow",
              "description": "Trace energy through food chains, food webs and trophic levels.",
              "minutes": 60,
              "level": 2,
              "videos": 5,
              "articles": 6
            },
            {
              "name": "Human Impact on the Environment",
              "description": "Analyze how human activity affects ecosystems, biodiversity and resources.",
              "minutes": 114,
              "level": 2,
              "videos": 8,
              "articles": 10
            },
            {
              "name": "Carrying Capacity",
              "description": "Explain how limiting factors set the carrying capacity of a population.",
              "minutes": 49,
              "level": 2,
              "videos": 5,
              "articles": 6
            },
            {
              "name": "Symbiosis",
              "description": "Distinguish mutualism, commensalism and parasitism with examples.",
              "minutes": 51,
              "level": 1,
              "videos": 4,
              "articles": 3
            }
          ]
        }
      ]
    },
    {
      "name": "Physical Science",
      "weight": 40,
      "topics": [
        {
          "name": "Chemistry",
          "subtopics": [
            {
              "name": "Atomic Structure & Properties of Matter",
              "description": "Describe atoms, the periodic table and how structure determines a substance's properties.",
              "minutes": 212,
              "level": 3,
              "videos": 17,
              "articles": 9
            },
            {
              "name": "States of Matter",
              "description": "Explain solids, liquids and gases and the changes between them in terms of particle motion.",
              "minutes": 133,
              "level": 1,
              "videos": 13,
              "articles": 0
            },
            {
              "name": "Solutions & Solubility",
              "description": "Describe solutions and concentration, and what affects how much of a substance dissolves.",
              "minutes": 92,
              "level": 2,
              "videos": 7,
              "articles": 3
            },
            {
              "name": "Chemical Equations & Energy Changes",
              "description": "Balance chemical equations and classify reactions as exothermic or endothermic.",
              "minutes": 121,
              "level": 3,
              "videos": 10,
              "articles": 3
            }
          ]
        },
        {
          "name": "Physics",
          "subtopics": [
            {
              "name": "Motion & Newton's Laws",
              "description": "Calculate speed, velocity and acceleration, and apply Newton's three laws of motion.",
              "minutes": 184,
              "level": 3,
              "videos": 13,
              "articles": 2
            },
            {
              "name": "Types & Transformations of Energy",
              "description": "Identify forms of energy and describe how energy changes form while being conserved.",
              "minutes": 51,
              "level": 2,
              "videos": 3,
              "articles": 0
            },
            {
              "name": "Energy Sources",
              "description": "Compare fossil, nuclear and renewable energy sources and their trade-offs.",
              "minutes": 87,
              "level": 2,
              "videos": 6,
              "articles": 0
            },
            {
              "name": "Heat & Heat Transfer",
              "description": "Distinguish heat from temperature and explain conduction, convection and radiation.",
              "minutes": 61,
              "level": 2,
              "videos": 4,
              "articles": 0
            },
            {
              "name": "Work & Simple Machines",
              "description": "Calculate work and explain how simple machines trade force for distance.",
              "minutes": 25,
              "level": 2,
              "videos": 1,
              "articles": 1
            },
            {
              "name": "Waves & Sound",
              "description": "Describe wave properties and how sound travels.",
              "minutes": 55,
              "level": 2,
              "videos": 4,
              "articles": 1
            },
            {
              "name": "Light",
              "description": "Explain the electromagnetic spectrum, reflection and refraction.",
              "minutes": 151,
              "level": 2,
              "videos": 8,
              "articles": 3
            },
            {
              "name": "Magnetism",
              "description": "Describe magnetic fields and how electricity and magnetism produce each other.",
              "minutes": 153,
              "level": 3,
              "videos": 11,
              "articles": 0
            }
          ]
        }
      ]
    },
    {
      "name": "Earth & Space Science",
      "weight": 20,
      "topics": [
        {
          "name": "Earth Systems",
          "subtopics": [
            {
              "name": "Plate Tectonics, Volcanoes & Earthquakes",
              "description": "Explain plate movement and how it causes earthquakes, volcanoes and mountains.",
              "minutes": 100,
              "level": 2,
              "videos": 7,
              "articles": 9
            },
            {
              "name": "Weather & Climate Change",
              "description": "Distinguish weather from climate and explain the causes and effects of climate change.",
              "minutes": 80,
              "level": 2,
              "videos": 5,
              "articles": 7
            },
            {
              "name": "Oceans & Currents",
              "description": "Explain what drives ocean currents and how they affect climate.",
              "minutes": 15,
              "level": 2,
              "videos": 1,
              "articles": 1
            },
            {
              "name": "Cycles of Matter",
              "description": "Trace the water, carbon and nitrogen cycles through Earth's systems.",
              "minutes": 48,
              "level": 2,
              "videos": 5,
              "articles": 6
            },
            {
              "name": "Natural Hazards",
              "description": "Describe natural hazards and how people predict and reduce their impact.",
              "minutes": 15,
              "level": 1,
              "videos": 1,
              "articles": 1
            },
            {
              "name": "Natural Resources & Sustainability",
              "description": "Compare renewable and nonrenewable resources and how they can be managed sustainably.",
              "minutes": 40,
              "level": 2,
              "videos": 3,
              "articles": 3
            }
          ]
        },
        {
          "name": "Space & Earth History",
          "subtopics": [
            {
              "name": "The Solar System & Stars",
              "description": "Describe the solar system and the life cycle of stars.",
              "minutes": 113,
              "level": 2,
              "videos": 7,
              "articles": 4
            },
            {
              "name": "Earth's Age, Rock Layers & Fossils",
              "description": "Use rock layers and fossils to reason about Earth's age and history.",
              "minutes": 21,
              "level": 2,
              "videos": 2,
              "articles": 1
            }
          ]
        }
      ]
    }
  ]
};
